I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 44, in script call
    call show_dialogue("titus")
  File "game/script.rpy", line 195, in script
    if character == "titus":
  File "game/script.rpy", line 195, in <module>
    if character == "titus":
NameError: name 'character' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 44, in script call
    call show_dialogue("titus")
  File "game/script.rpy", line 195, in script
    if character == "titus":
  File "C:\Users\Leonela\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Leonela\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Leonela\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 195, in <module>
    if character == "titus":
NameError: name 'character' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Celler_de_mites 1.0
Wed Oct 30 05:39:11 2024
